#!/bin/bash
# Manual n8n Workflow Import Instructions

echo "========================================"
echo "   n8n Workflow Import Guide"
echo "========================================"
echo ""
echo "n8n is running at: http://localhost:5678"
echo ""
echo "To import the Telegram Command Handler workflow:"
echo ""
echo "STEP 1: Open browser"
echo "  → Go to http://localhost:5678"
echo ""
echo "STEP 2: Import workflow"
echo "  → Click 'Workflows' in the left menu"
echo "  → Click the '...' button (top right)"
echo "  → Select 'Import from File'"
echo "  → Choose this file:"
echo "    ~/openclaw/workspace/n8n/workflows/telegram_command_handler.json"
echo ""
echo "STEP 3: Activate"
echo "  → Click the toggle button to activate"
echo ""
echo "STEP 4: Set up Telegram Bot (optional)"
echo "  → Create a bot via @BotFather on Telegram"
echo "  → Get your bot token"
echo "  → Add Telegram node in n8n and paste token"
echo ""
echo "========================================"
